const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.List,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Behaviors.Persist,
		C3.Plugins.TextBox,
		C3.Plugins.iframe,
		C3.Plugins.NinePatch,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Rotate,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Cnds.CompareSelection,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.List.Acts.AddItemAt,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.List.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.JavaScriptInEvents.EventSheet7_Event3,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.JavaScriptInEvents.EventSheet8_Event2,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.JavaScriptInEvents.EventSheet9_Event3,
		C3.Plugins.iframe.Acts.NavigateURL,
		C3.JavaScriptInEvents.EventSheet10_Event4,
		C3.JavaScriptInEvents.EventSheet10_Event7,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.iframe.Acts.SetSize,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.iframe.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.loopindex,
		C3.JavaScriptInEvents.EventSheet11_Event24,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.Height,
		C3.JavaScriptInEvents.EventSheet11_Event73,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.JavaScriptInEvents.EventSheet12_Event6,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.List.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.List.Cnds.PickChildren,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.List.Acts.SetSize,
		C3.Plugins.List.Acts.SetVisible,
		C3.Plugins.List.Acts.SetEnabled,
		C3.Plugins.List.Acts.SetBoolInstanceVar,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.JavaScriptInEvents.EventSheetConsumos_Event4,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.List.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.JavaScriptInEvents.EventSheetFinal_Event2,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.FillEllipse,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.DrawingCanvas.Acts.SetEffect,
		C3.Plugins.DrawingCanvas.Acts.ResetPoly,
		C3.Plugins.DrawingCanvas.Acts.AddPolyPoint,
		C3.Plugins.DrawingCanvas.Acts.LinePoly,
		C3.Plugins.DrawingCanvas.Acts.FillPoly,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.NinePatch.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{fondo: 0},
	{titulo: 0},
	{Hx: 0},
	{Hy: 0},
	{Vx: 0},
	{Vy: 0},
	{input: 0},
	{Seleccionado: 0},
	{ListRegion: 0},
	{ListComuna: 0},
	{BaseScale: 0},
	{UpScale: 0},
	{btn_siguiente: 0},
	{btn_volver: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{JSON: 0},
	{AJAX: 0},
	{Browser: 0},
	{Array: 0},
	{ArrayRegiones: 0},
	{ArrayComunas: 0},
	{Dictionary: 0},
	{Persist: 0},
	{vivienda1: 0},
	{circulo1: 0},
	{vivienda2: 0},
	{vivienda3: 0},
	{circulo2: 0},
	{circulo3: 0},
	{Active: 0},
	{btn_radio1: 0},
	{btn_radio2: 0},
	{btn_radio3: 0},
	{btn_piso1: 0},
	{btn_piso2: 0},
	{btn_piso3: 0},
	{btn_radio4: 0},
	{btn_radio5: 0},
	{btn_radio6: 0},
	{btn_si: 0},
	{btn_no: 0},
	{id: 0},
	{btn_anio: 0},
	{Valor: 0},
	{TextInputMetros: 0},
	{clima1: 0},
	{clima2: 0},
	{clima3: 0},
	{clima4: 0},
	{circulo4: 0},
	{energia1: 0},
	{energia2: 0},
	{energia3: 0},
	{energia4: 0},
	{energia5: 0},
	{energia6: 0},
	{iframe: 0},
	{mes: 0},
	{input_mes: 0},
	{Frame: 0},
	{sp_boleta: 0},
	{fondo_mes: 0},
	{assetsform: 0},
	{Sprite: 0},
	{cerrar_popup: 0},
	{assetsform2: 0},
	{assetsform3: 0},
	{assetsform4: 0},
	{Lista: 0},
	{ListaDormitorio: 0},
	{Layer: 0},
	{Used: 0},
	{tipo_consumo: 0},
	{BotonConsejo: 0},
	{ID: 0},
	{recomendacion: 0},
	{ahorro: 0},
	{ID_Web: 0},
	{GrupoId: 0},
	{FrameInversion: 0},
	{Cargado: 0},
	{IDGrupo: 0},
	{Imagen: 0},
	{Tipo: 0},
	{assetsform5: 0},
	{Activado: 0},
	{tipo: 0},
	{Activated: 0},
	{CheckboxAgua: 0},
	{Text: 0},
	{assetsform6: 0},
	{Total: 0},
	{assetsform7: 0},
	{boton_adelante: 0},
	{Sprite2: 0},
	{CheckboxElectrodomesticos: 0},
	{CheckboxCalefaccion: 0},
	{TotalCalefaccion: 0},
	{TotalElectrodomesticos: 0},
	{CheckboxCocina: 0},
	{TotalCocina: 0},
	{CheckboxIluminacion: 0},
	{TotalIluminacion: 0},
	{TotalEnfriamiento: 0},
	{CheckboxEnfriamiento: 0},
	{ArrayBotones: 0},
	{assetsform8: 0},
	{Text2: 0},
	{Text3: 0},
	{assetsform9: 0},
	{Ministeriodeenergia: 0},
	{EstrellaIluminacion: 0},
	{EstrellaElectrodomesticos: 0},
	{EstrellaCocina: 0},
	{EstrellaEnfriamiento: 0},
	{EstrellaCalefaccion: 0},
	{EstrellaAgua: 0},
	{Text4: 0},
	{barraActual: 0},
	{Barra: 0},
	{assetsform12: 0},
	{TextKwh: 0},
	{TextKwh2: 0},
	{btn_si2: 0},
	{btn_no2: 0},
	{LayerAbrir: 0},
	{ValorConsumo: 0},
	{TipoConsumo: 0},
	{assetsform11_GLP: 0},
	{assetsform13_GN: 0},
	{assetsform14_kerosene: 0},
	{assetsform15_pellet: 0},
	{assetsform16_lena: 0},
	{assetsform17_electricidad: 0},
	{assetsform18: 0},
	{Usado: 0},
	{ProyectoNuevo: 0},
	{input2: 0},
	{"9patch": 0},
	{actualOption: 0},
	{ListaGLP: 0},
	{ResultadoGasText: 0},
	{ConsumoText: 0},
	{ConsumoText2: 0},
	{LayerActual: 0},
	{Combustible: 0},
	{btn_cancelar: 0},
	{input_Kerosene: 0},
	{assetsform19: 0},
	{input_Pellets: 0},
	{input_Lena: 0},
	{input_mes2: 0},
	{Lapiz: 0},
	{isSubtitulo: 0},
	{tituloJuntos: 0},
	{Form: 0},
	{Form2: 0},
	{Sprite3: 0},
	{barraMejora: 0},
	{TextKwhMejora: 0},
	{btn_siguiente2: 0},
	{PlatformInfo: 0},
	{VX: 0},
	{VY: 0},
	{HX: 0},
	{HY: 0},
	{ScaleH: 0},
	{ScaleV: 0},
	{Holder: 0},
	{Mostrar: 0},
	{Tooltip: 0},
	{assetsform23: 0},
	{"9patch2": 0},
	{marcoinfo: 0},
	{marcoComentario: 0},
	{btn_ok: 0},
	{Screenshot_: 0},
	{Screenshot_2: 0},
	{Sprite4: 0},
	{Descargar: 0},
	{tituloBoleta: 0},
	{ArrayInfoWeb: 0},
	{TextRecomendacion: 0},
	{TextPorcentaje: 0},
	{TextKwh_max: 0},
	{fondoTextKwh: 0},
	{assetsform10: 0},
	{assetsform11: 0},
	{assetsform13: 0},
	{assetsform14: 0},
	{assetsform15: 0},
	{assetsform16: 0},
	{assetsform17: 0},
	{assetsform21: 0},
	{assetsform24: 0},
	{assetsform25: 0},
	{text_consumo_actual: 0},
	{text_ahorro_potencia: 0},
	{text_porcentaje_ahorro1: 0},
	{text_porcentaje_ahorro2: 0},
	{text_porcentaje_ahorro3: 0},
	{text_porcentaje_ahorro4: 0},
	{text_porcentaje_ahorro5: 0},
	{text_porcentaje_ahorro6: 0},
	{assetsform26: 0},
	{text_ahorro_anual: 0},
	{text_carbono: 0},
	{text_inversion: 0},
	{TextKwh_titulo: 0},
	{TextKwhMejora_titulo: 0},
	{Sprite5: 0},
	{Rotate: 0},
	{Loading_icon: 0},
	{CerrarPopup: 0},
	{assetsform27: 0},
	{assetsform28: 0},
	{assetsform29: 0},
	{assetsform30: 0},
	{textoRecomendacion: 0},
	{Pos1: 0},
	{Pos2: 0},
	{Sprite6: 0},
	{Textahorro: 0},
	{RecomendacionesmarcoFinal: 0},
	{assetsform32: 0},
	{HWidth: 0},
	{HHeight: 0},
	{VWidth: 0},
	{VHeight: 0},
	{TextRecomendacionFin: 0},
	{botonCambiar: 0},
	{iconoCambiar: 0},
	{PorcentajeText: 0},
	{Desglose: 0},
	{assetsform34: 0},
	{Porcentaje: 0},
	{Consumo: 0},
	{CirculoPorcentaje: 0},
	{MarcoConsumo: 0},
	{ConsumoPantallaFin: 0},
	{DrawingCanvas: 0},
	{ArrayTipos: 0},
	{assetsform35: 0},
	{assetsform36: 0},
	{MarcoRecomendaciones: 0},
	{tituloPagina: 0},
	{tituloAnoConstruccion: 0},
	{tituloTamanoVivienda: 0},
	{tituloIndique: 0},
	{tituloIndiqueDormitorios: 0},
	{Sprite7: 0},
	{tituloLapiz: 0},
	{Lapiz2: 0},
	{tituloTooltip: 0},
	{tituloglp2: 0},
	{tituloglp: 0},
	{tituloKer2: 0},
	{tituloKer: 0},
	{tituloPell2: 0},
	{tituloPell: 0},
	{tituloLen2: 0},
	{tituloLen: 0},
	{tituloElec2: 0},
	{tituloGN2: 0},
	{tituloRecomendaciones2: 0},
	{tituloSubRecomendacion: 0},
	{BajadaFin: 0},
	{tituloasd: 0},
	{SpriteMin: 0},
	{SpriteMax: 0},
	{FamilyButton: 0},
	{FamilyRadioButton: 0},
	{Estrellas: 0},
	{Checkbox: 0},
	{TextosTotal: 0},
	{Climas: 0},
	{Consumos: 0},
	{consumosText: 0},
	{Inputs: 0},
	{BotonesSprite: 0},
	{Titulos: 0},
	{Listas: 0},
	{MarcosFin: 0},
	{idk: 0},
	{idkText: 0},
	{idkList: 0},
	{idkInputs: 0},
	{i: 0},
	{comuna_nombre: 0},
	{comuna_id: 0},
	{comuna_clima: 0},
	{j: 0},
	{IndexRecomendacion: 0},
	{a_region: 0},
	{a_region_index: 0},
	{a_comuna: 0},
	{a_comuna_id: 0},
	{paso_completado: 0},
	{a_tipo_vivienda: 0},
	{a_casa_pisos: 0},
	{a_departamento_pisos: 0},
	{a_anio_construccion: 0},
	{a_conoce_superficie: 0},
	{a_superficie: 0},
	{a_dormitorios: 0},
	{a_tipo_clima: 0},
	{a_usa_glp: 0},
	{a_usa_gn: 0},
	{a_usa_ker: 0},
	{a_usa_pel: 0},
	{a_usa_len: 0},
	{a_usa_elec: 0},
	{a_ultimo_piso: 0},
	{a_conoce_consumos: 0},
	{a_edita_equipos: 0},
	{a_consumo_id: 0},
	{a_consumo_elec: 0},
	{a_consumo_gn: 0},
	{a_consumo_glp: 0},
	{a_consumo_ker: 0},
	{a_consumo_len: 0},
	{a_consumo_pel: 0},
	{a_consumo_mes1Elec: 0},
	{a_consumo_mes2Elec: 0},
	{a_consumo_mes3Elec: 0},
	{a_consumo_mes4Elec: 0},
	{a_consumo_mes5Elec: 0},
	{a_consumo_mes6Elec: 0},
	{a_consumo_mes7Elec: 0},
	{a_consumo_mes8Elec: 0},
	{a_consumo_mes9Elec: 0},
	{a_consumo_mes10Elec: 0},
	{a_consumo_mes11Elec: 0},
	{a_consumo_mes12Elec: 0},
	{a_consumo_mes1GN: 0},
	{a_consumo_mes2GN: 0},
	{a_consumo_mes3GN: 0},
	{a_consumo_mes4GN: 0},
	{a_consumo_mes5GN: 0},
	{a_consumo_mes6GN: 0},
	{a_consumo_mes7GN: 0},
	{a_consumo_mes8GN: 0},
	{a_consumo_mes9GN: 0},
	{a_consumo_mes10GN: 0},
	{a_consumo_mes11GN: 0},
	{a_consumo_mes12GN: 0},
	{Width: 0},
	{Height: 0},
	{Aspect: 0},
	{IsPortrait: 0},
	{url_end_point: 0},
	{url_iframe_3d: 0},
	{CasaODepartamento: 0},
	{eligioPiso: 0},
	{RegionElegida: 0},
	{i2: 0},
	{comuna_nombre2: 0},
	{comuna_id2: 0},
	{comuna_clima2: 0},
	{j2: 0},
	{MostrarConsumos: 0},
	{CantidadAgua: 0},
	{CantidadRecomendacines: 0},
	{CantidadElectrodomesticos: 0},
	{CantidadCalefaccion: 0},
	{CantidadCocina: 0},
	{CantidadIluminacion: 0},
	{CantidadEnfriamiento: 0},
	{BotonesApretados: 0},
	{IdSeleccionados: 0},
	{TextoActual: 0},
	{TipoActual: 0},
	{IndiceTextos: 0},
	{tieneRecomendaciones: 0},
	{tipoConsumoUsed1: 0},
	{tipoConsumoUsed2: 0},
	{tipoConsumoUsed3: 0},
	{tipoConsumoUsed4: 0},
	{tipoConsumoUsed5: 0},
	{tipoConsumoUsed6: 0},
	{AuxContadorFichas: 0},
	{dda_energia_max: 0},
	{index: 0},
	{grupo_uso_id: 0},
	{grupoUsoId: 0},
	{grupoUso: 0},
	{grupoUsoCorto: 0},
	{imagenTarjeta: 0},
	{inversionId: 0},
	{inversion: 0},
	{ahorroEeId: 0},
	{ahorroEe: 0},
	{tipoConsumo_fila1: 0},
	{tipoConsumo_fila2: 0},
	{tipoConsumo_columna1: 0},
	{tipoConsumo_columna2: 0},
	{tipoConsumo_columna3: 0},
	{tipoConsumo_fila3: 0},
	{tipoConsumo_fila4: 0},
	{tipoConsumo_fila5: 0},
	{tipoConsumo_columna4: 0},
	{tipoConsumo_columna5: 0},
	{tipoConsumo_boton_diffFila: 0},
	{tipoConsumo_boton_diffColumna: 0},
	{tipoConsumo_text_diffFila: 0},
	{tipoConsumo_text_diffColumna: 0},
	{orden: 0},
	{consumo: 0},
	{actualiza_mejora: 0},
	{valor: 0},
	{valorMin: 0},
	{valorMax: 0},
	{posicionMin: 0},
	{posicionMax: 0},
	{EstrellasIluminacion: 0},
	{EstrellasElectrodomesticos: 0},
	{EstrellasCocina: 0},
	{EstrellasEnfriamiento: 0},
	{EstrellasCalefaccion: 0},
	{EstrellasAgua: 0},
	{PantallaActual: 0},
	{CantidadPantallas: 0},
	{KWhAnual: 0},
	{KWhAnualMejora: 0},
	{ahorro_energetico_promedio: 0},
	{ahorro_porcentaje_consumo_calefaccion: 0},
	{ahorro_porcentaje_consumo_agua: 0},
	{ahorro_porcentaje_consumo_electrodomestico: 0},
	{ahorro_porcentaje_consumo_enfriamiento: 0},
	{ahorro_porcentaje_consumo_cocina: 0},
	{ahorro_porcentaje_consumo_iluminacion: 0},
	{ahorro_promedio_monetario: 0},
	{YIndex: 0},
	{XIndex: 0},
	{Contador: 0},
	{AuxContador: 0},
	{LayerInicial: 0},
	{numero1: 0},
	{AuxBool: 0},
	{BoolPisos: 0},
	{numero: 0},
	{testValor: 0},
	{Gases5: 0},
	{Gases5Aux: 0},
	{Gases11: 0},
	{Gases11Aux: 0},
	{Gases15: 0},
	{Gases15Aux: 0},
	{Gases45: 0},
	{PrimeraVez: 0},
	{Gases45Aux: 0},
	{textoIluminacion: 0},
	{textoCocina: 0},
	{textoElectrodomesticos: 0},
	{textoAgua: 0},
	{textoEnfriamiento: 0},
	{textoCalefaccion: 0},
	{boolIluminacion: 0},
	{boolCocina: 0},
	{boolElectrodomesticos: 0},
	{boolAgua: 0},
	{boolEnfriamiento: 0},
	{boolCalefaccion: 0},
	{Mostrar1Bool: 0},
	{centroX: 0},
	{centroY: 0},
	{radio: 0},
	{suavizado: 0},
	{porcentaje1: 0},
	{porcentaje2: 0},
	{porcentaje3: 0},
	{porcentaje4: 0},
	{porcentaje5: 0},
	{porcentaje6: 0},
	{NumeroFichas: 0},
	{Par: 0},
	{IndiceFrame: 0},
	{AuxIluminacion: 0},
	{AuxCocina: 0},
	{AuxElectrodomesticos: 0},
	{AuxAgua: 0},
	{AuxEnfriamiento: 0},
	{AuxCalefaccion: 0},
	{grupo_uso: 0},
	{anguloInicio: 0},
	{anguloFinal: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{texto: 0},
	{es_titulo: 0},
	{es_espacio: 0},
	{grupo_id: 0},
	{linea_inicio: 0},
	{cantidad_lineas: 0}
];

self.InstanceType = {
	fondo: class extends self.ISpriteInstance {},
	titulo: class extends self.ITextInstance {},
	input: class extends self.ISpriteInstance {},
	ListRegion: class extends self.IListInstance {},
	ListComuna: class extends self.IListInstance {},
	btn_siguiente: class extends self.ISpriteInstance {},
	btn_volver: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	ArrayRegiones: class extends self.IArrayInstance {},
	ArrayComunas: class extends self.IArrayInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	vivienda1: class extends self.ISpriteInstance {},
	circulo1: class extends self.ISpriteInstance {},
	vivienda2: class extends self.ISpriteInstance {},
	vivienda3: class extends self.ISpriteInstance {},
	circulo2: class extends self.ISpriteInstance {},
	circulo3: class extends self.ISpriteInstance {},
	btn_radio1: class extends self.ISpriteInstance {},
	btn_radio2: class extends self.ISpriteInstance {},
	btn_radio3: class extends self.ISpriteInstance {},
	btn_piso1: class extends self.ISpriteInstance {},
	btn_piso2: class extends self.ISpriteInstance {},
	btn_piso3: class extends self.ISpriteInstance {},
	btn_radio4: class extends self.ISpriteInstance {},
	btn_radio5: class extends self.ISpriteInstance {},
	btn_radio6: class extends self.ISpriteInstance {},
	btn_si: class extends self.ISpriteInstance {},
	btn_no: class extends self.ISpriteInstance {},
	btn_anio: class extends self.ISpriteInstance {},
	TextInputMetros: class extends self.ITextInputInstance {},
	clima1: class extends self.ISpriteInstance {},
	clima2: class extends self.ISpriteInstance {},
	clima3: class extends self.ISpriteInstance {},
	clima4: class extends self.ISpriteInstance {},
	circulo4: class extends self.ISpriteInstance {},
	energia1: class extends self.ISpriteInstance {},
	energia2: class extends self.ISpriteInstance {},
	energia3: class extends self.ISpriteInstance {},
	energia4: class extends self.ISpriteInstance {},
	energia5: class extends self.ISpriteInstance {},
	energia6: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	input_mes: class extends self.ITextInputInstance {},
	sp_boleta: class extends self.ISpriteInstance {},
	fondo_mes: class extends self.ISpriteInstance {},
	assetsform: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	cerrar_popup: class extends self.ISpriteInstance {},
	assetsform2: class extends self.ISpriteInstance {},
	assetsform3: class extends self.ISpriteInstance {},
	assetsform4: class extends self.ISpriteInstance {},
	Lista: class extends self.IListInstance {},
	ListaDormitorio: class extends self.IListInstance {},
	BotonConsejo: class extends self.ISpriteInstance {},
	assetsform5: class extends self.ISpriteInstance {},
	CheckboxAgua: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	assetsform6: class extends self.ISpriteInstance {},
	Total: class extends self.ITextInstance {},
	assetsform7: class extends self.ISpriteInstance {},
	boton_adelante: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	CheckboxElectrodomesticos: class extends self.ISpriteInstance {},
	CheckboxCalefaccion: class extends self.ISpriteInstance {},
	TotalCalefaccion: class extends self.ITextInstance {},
	TotalElectrodomesticos: class extends self.ITextInstance {},
	CheckboxCocina: class extends self.ISpriteInstance {},
	TotalCocina: class extends self.ITextInstance {},
	CheckboxIluminacion: class extends self.ISpriteInstance {},
	TotalIluminacion: class extends self.ITextInstance {},
	TotalEnfriamiento: class extends self.ITextInstance {},
	CheckboxEnfriamiento: class extends self.ISpriteInstance {},
	ArrayBotones: class extends self.IArrayInstance {},
	assetsform8: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	assetsform9: class extends self.ISpriteInstance {},
	Ministeriodeenergia: class extends self.ISpriteInstance {},
	EstrellaIluminacion: class extends self.ISpriteInstance {},
	EstrellaElectrodomesticos: class extends self.ISpriteInstance {},
	EstrellaCocina: class extends self.ISpriteInstance {},
	EstrellaEnfriamiento: class extends self.ISpriteInstance {},
	EstrellaCalefaccion: class extends self.ISpriteInstance {},
	EstrellaAgua: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	barraActual: class extends self.ISpriteInstance {},
	Barra: class extends self.ISpriteInstance {},
	assetsform12: class extends self.ISpriteInstance {},
	TextKwh: class extends self.ITextInstance {},
	TextKwh2: class extends self.ITextInstance {},
	btn_si2: class extends self.ISpriteInstance {},
	btn_no2: class extends self.ISpriteInstance {},
	assetsform11_GLP: class extends self.ISpriteInstance {},
	assetsform13_GN: class extends self.ISpriteInstance {},
	assetsform14_kerosene: class extends self.ISpriteInstance {},
	assetsform15_pellet: class extends self.ISpriteInstance {},
	assetsform16_lena: class extends self.ISpriteInstance {},
	assetsform17_electricidad: class extends self.ISpriteInstance {},
	assetsform18: class extends self.ISpriteInstance {},
	ProyectoNuevo: class extends self.ISpriteInstance {},
	input2: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	ListaGLP: class extends self.IListInstance {},
	ResultadoGasText: class extends self.ITextInstance {},
	ConsumoText: class extends self.ITextInstance {},
	ConsumoText2: class extends self.ITextInstance {},
	btn_cancelar: class extends self.ISpriteInstance {},
	input_Kerosene: class extends self.ITextInputInstance {},
	assetsform19: class extends self.ISpriteInstance {},
	input_Pellets: class extends self.ITextInputInstance {},
	input_Lena: class extends self.ITextInputInstance {},
	input_mes2: class extends self.ITextInputInstance {},
	Lapiz: class extends self.ISpriteInstance {},
	tituloJuntos: class extends self.ITextInstance {},
	Form: class extends self.ISpriteInstance {},
	Form2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	barraMejora: class extends self.ISpriteInstance {},
	TextKwhMejora: class extends self.ITextInstance {},
	btn_siguiente2: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Holder: class extends self.ISpriteInstance {},
	Tooltip: class extends self.ISpriteInstance {},
	assetsform23: class extends self.ISpriteInstance {},
	_9patch2: class extends self.IWorldInstance {},
	marcoinfo: class extends self.ISpriteInstance {},
	marcoComentario: class extends self.ISpriteInstance {},
	btn_ok: class extends self.ISpriteInstance {},
	Screenshot_: class extends self.ISpriteInstance {},
	Screenshot_2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Descargar: class extends self.ISpriteInstance {},
	tituloBoleta: class extends self.ITextInstance {},
	ArrayInfoWeb: class extends self.IArrayInstance {},
	TextRecomendacion: class extends self.ITextInstance {},
	TextPorcentaje: class extends self.ITextInstance {},
	TextKwh_max: class extends self.ITextInstance {},
	fondoTextKwh: class extends self.ISpriteInstance {},
	assetsform10: class extends self.ISpriteInstance {},
	assetsform11: class extends self.ISpriteInstance {},
	assetsform13: class extends self.ISpriteInstance {},
	assetsform14: class extends self.ISpriteInstance {},
	assetsform15: class extends self.ISpriteInstance {},
	assetsform16: class extends self.ISpriteInstance {},
	assetsform17: class extends self.ISpriteInstance {},
	assetsform21: class extends self.ISpriteInstance {},
	assetsform24: class extends self.ISpriteInstance {},
	assetsform25: class extends self.ISpriteInstance {},
	text_consumo_actual: class extends self.ITextInstance {},
	text_ahorro_potencia: class extends self.ITextInstance {},
	text_porcentaje_ahorro1: class extends self.ITextInstance {},
	text_porcentaje_ahorro2: class extends self.ITextInstance {},
	text_porcentaje_ahorro3: class extends self.ITextInstance {},
	text_porcentaje_ahorro4: class extends self.ITextInstance {},
	text_porcentaje_ahorro5: class extends self.ITextInstance {},
	text_porcentaje_ahorro6: class extends self.ITextInstance {},
	assetsform26: class extends self.ISpriteInstance {},
	text_ahorro_anual: class extends self.ITextInstance {},
	text_carbono: class extends self.ITextInstance {},
	text_inversion: class extends self.ITextInstance {},
	TextKwh_titulo: class extends self.ITextInstance {},
	TextKwhMejora_titulo: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Loading_icon: class extends self.ISpriteInstance {},
	CerrarPopup: class extends self.ISpriteInstance {},
	assetsform27: class extends self.ISpriteInstance {},
	assetsform28: class extends self.ISpriteInstance {},
	assetsform29: class extends self.ISpriteInstance {},
	assetsform30: class extends self.ISpriteInstance {},
	textoRecomendacion: class extends self.ITextInstance {},
	Pos1: class extends self.ISpriteInstance {},
	Pos2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Textahorro: class extends self.ITextInstance {},
	RecomendacionesmarcoFinal: class extends self.ISpriteInstance {},
	assetsform32: class extends self.ISpriteInstance {},
	TextRecomendacionFin: class extends self.ITextInstance {},
	botonCambiar: class extends self.ISpriteInstance {},
	iconoCambiar: class extends self.ISpriteInstance {},
	PorcentajeText: class extends self.ITextInstance {},
	Desglose: class extends self.ISpriteInstance {},
	assetsform34: class extends self.ISpriteInstance {},
	CirculoPorcentaje: class extends self.ISpriteInstance {},
	MarcoConsumo: class extends self.ISpriteInstance {},
	ConsumoPantallaFin: class extends self.ITextInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	ArrayTipos: class extends self.IArrayInstance {},
	assetsform35: class extends self.ISpriteInstance {},
	assetsform36: class extends self.ISpriteInstance {},
	MarcoRecomendaciones: class extends self.IWorldInstance {},
	tituloPagina: class extends self.ITextInstance {},
	tituloAnoConstruccion: class extends self.ITextInstance {},
	tituloTamanoVivienda: class extends self.ITextInstance {},
	tituloIndique: class extends self.ITextInstance {},
	tituloIndiqueDormitorios: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	tituloLapiz: class extends self.ITextInstance {},
	Lapiz2: class extends self.ISpriteInstance {},
	tituloTooltip: class extends self.ITextInstance {},
	tituloglp2: class extends self.ITextInstance {},
	tituloglp: class extends self.ITextInstance {},
	tituloKer2: class extends self.ITextInstance {},
	tituloKer: class extends self.ITextInstance {},
	tituloPell2: class extends self.ITextInstance {},
	tituloPell: class extends self.ITextInstance {},
	tituloLen2: class extends self.ITextInstance {},
	tituloLen: class extends self.ITextInstance {},
	tituloElec2: class extends self.ITextInstance {},
	tituloGN2: class extends self.ITextInstance {},
	tituloRecomendaciones2: class extends self.ITextInstance {},
	tituloSubRecomendacion: class extends self.ITextInstance {},
	BajadaFin: class extends self.ITextInstance {},
	tituloasd: class extends self.ITextInstance {},
	SpriteMin: class extends self.ISpriteInstance {},
	SpriteMax: class extends self.ISpriteInstance {},
	FamilyButton: class extends self.ISpriteInstance {},
	FamilyRadioButton: class extends self.ISpriteInstance {},
	Estrellas: class extends self.ISpriteInstance {},
	Checkbox: class extends self.ISpriteInstance {},
	TextosTotal: class extends self.ITextInstance {},
	Climas: class extends self.ISpriteInstance {},
	Consumos: class extends self.ISpriteInstance {},
	consumosText: class extends self.ITextInstance {},
	Inputs: class extends self.ITextInputInstance {},
	BotonesSprite: class extends self.ISpriteInstance {},
	Titulos: class extends self.ITextInstance {},
	Listas: class extends self.IListInstance {},
	MarcosFin: class extends self.ISpriteInstance {},
	idk: class extends self.ISpriteInstance {},
	idkText: class extends self.ITextInstance {},
	idkList: class extends self.IListInstance {},
	idkInputs: class extends self.ITextInputInstance {}
}