# Usar una imagen oficial y ligera de Nginx
FROM nginx:stable-alpine

# Eliminar la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiar nuestra configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar los archivos de los dos proyectos de frontend
COPY Front-end/web-front /usr/share/nginx/html/web-front
COPY Front-end/casa_3d /usr/share/nginx/html/casa_3d