# Generated by Django 5.0.7 on 2024-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_casa_eficiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(blank=True, max_length=150, null=True)),
                ('grupo_uso_corto', models.CharField(blank=True, max_length=150, null=True)),
                ('espacio_exterior', models.BooleanField(blank=True, null=True, verbose_name='Exterior')),
                ('espacio_cocina', models.BooleanField(blank=True, null=True, verbose_name='Cocina')),
                ('espacio_bahno', models.BooleanField(blank=True, null=True, verbose_name='Baño')),
                ('espacio_dormitorio', models.BooleanField(blank=True, null=True, verbose_name='Dormitorio')),
                ('espacio_living', models.BooleanField(blank=True, null=True, verbose_name='Living-comedor')),
                ('descripcion', models.TextField(null=True)),
                ('energia_base_id', models.IntegerField(null=True)),
                ('grupo_uso_id', models.IntegerField(blank=True, null=True)),
                ('cantidad_promedio', models.IntegerField(blank=True, null=True)),
                ('horas_uso_tipo', models.FloatField(blank=True, null=True)),
                ('potencia_equipo', models.FloatField(blank=True, null=True)),
                ('eficiencia_equipo', models.FloatField(blank=True, null=True)),
                ('promedio_energia_anual', models.FloatField(blank=True, null=True)),
                ('fuente', models.TextField(null=True)),
            ],
        ),
    ]
