# Generated by Django 5.0.7 on 2025-01-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_casa_eficiente', '0002_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='etiqueta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='subtitulo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='imagen_tarjeta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
