# Generated by Django 5.0.7 on 2025-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_casa_eficiente', '0003_equipos_etiqueta_equipos_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energeticosfenomeno',
            name='unidad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
